filename = 'UAVCourseData_2Edited.mat';
save(filename,'cuboid','distToOtherTargets','hoopIR','hoopOR','hoopPsi',...
    'hoopTheta','hoopX','hoopY','hoopZ','insideCuboid','j','nCuboids','nDone',...
    'nHoops','nTargets','targetPos','targetScore','thisPos','xLim','xS','yLim','yS','zLim','zS')